"""Configurable single-event detection rules."""

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from lightweight_hids.models import Alert, Event


class RuleError(ValueError):
    """Raised when a detection-rule definition is invalid."""


@dataclass(frozen=True, slots=True)
class SingleEventRule:
    """A rule evaluated against one Event at a time."""

    rule_id: str
    event_type: str
    title: str
    description: str
    severity: str
    conditions: dict[str, Any]
    enabled: bool = True

    def matches(self, event: Event) -> bool:
        """Return True when the Event satisfies this rule."""
        if not self.enabled:
            return False

        if event.event_type != self.event_type:
            return False

        for field_name, expected_value in self.conditions.items():
            if field_name not in event.data:
                return False

            if event.data[field_name] != expected_value:
                return False

        return True


class RuleEngine:
    """Evaluate Events against configured single-event rules."""

    def __init__(self, rules: list[SingleEventRule]) -> None:
        self.rules = tuple(rules)

    def evaluate(self, event: Event) -> list[Alert]:
        """Return Alerts generated by rules matching the Event."""
        alerts: list[Alert] = []

        for rule in self.rules:
            if not rule.matches(event):
                continue

            alerts.append(
                Alert(
                    rule_id=rule.rule_id,
                    title=rule.title,
                    description=rule.description,
                    severity=rule.severity,
                    event_ids=[event.event_id],
                    evidence=dict(event.data),
                )
            )

        return alerts


def load_rules(path: str | Path) -> list[SingleEventRule]:
    """Load and validate single-event rules from YAML."""
    rules_path = Path(path)

    if not rules_path.is_file():
        raise RuleError(f"rules file not found: {rules_path}")

    with rules_path.open("r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    if not isinstance(data, dict) or not isinstance(data.get("rules"), list):
        raise RuleError("rules file must contain a rules list")

    loaded_rules: list[SingleEventRule] = []
    seen_ids: set[str] = set()

    for index, definition in enumerate(data["rules"]):
        if not isinstance(definition, dict):
            raise RuleError(f"rule at index {index} must be a mapping")

        required = (
            "id",
            "kind",
            "event_type",
            "title",
            "description",
            "severity",
        )

        for field_name in required:
            value = definition.get(field_name)

            if not isinstance(value, str) or not value.strip():
                raise RuleError(
                    f"rule at index {index} has invalid {field_name}"
                )

        rule_id = definition["id"]

        if rule_id in seen_ids:
            raise RuleError(f"duplicate rule id: {rule_id}")

        if definition["kind"] != "single_event":
            raise RuleError(
                f"unsupported rule kind: {definition['kind']}"
            )

        severity = definition["severity"]

        if severity not in Alert.ALLOWED_SEVERITIES:
            raise RuleError(f"invalid severity for rule {rule_id}")

        enabled = definition.get("enabled", True)

        if not isinstance(enabled, bool):
            raise RuleError(f"enabled must be boolean for rule {rule_id}")

        conditions = definition.get("conditions", {})

        if not isinstance(conditions, dict):
            raise RuleError(
                f"conditions must be a mapping for rule {rule_id}"
            )

        loaded_rules.append(
            SingleEventRule(
                rule_id=rule_id,
                event_type=definition["event_type"],
                title=definition["title"],
                description=definition["description"],
                severity=severity,
                conditions=conditions,
                enabled=enabled,
            )
        )
        seen_ids.add(rule_id)

    return loaded_rules